name: Update README FOR GITHUB WORK

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@v0.1.6
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}